apiVersion: v1
kind: Service
metadata:
  name: {{ include "mario.fullname" . }}
  labels:
    {{- include "mario.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: {{ .Values.service.protocol }}
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "{{ .Values.service.lbenable }}"
    service.beta.kubernetes.io/aws-load-balancer-type: {{ .Values.service.lbtype }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mario.selectorLabels" . | nindent 4 }}
